spring.application.name=bad-performance-sample

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:15432/customs}
spring.datasource.username=${DB_USERNAME:customs}
spring.datasource.password=${DB_PASSWORD:customs}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=4
